# Sample data {#sec-sampledata}

The table below provides an overview of the raster and vector data used in this tutorial, including a link to source. In addition, a few potentially useful data sources are provided. For a much more extensive list of curated list of public data sets, see [this link](https://github.com/awesomedata/awesome-public-datasets).

### Data in this tutorial {.unnumbered}

The table below provides an overview of the data used in this tutorial. If you skipped @#sec-baselayers, you can download the files described in that section as a project [here](https://nx66306.your-storageshare.de/s/sLBsLt9xjK75bCx). Download the SDM.zip file and unzip it to your GRASSdb. If you already created a SDM project, replace it, or first rename it.

| Section | Name + link | Type |
|------------------------|------------------------|------------------------|
| @sec-nationalboundaries | [1:10m Admin 0 - Countries](https://www.naturalearthdata.com/downloads/10m-cultural-vectors/) | vector |
| @sec-roads | [roads](https://www.naturalearthdata.com/downloads/10m-cultural-vectors/roads/) | vector |
| @sec-rivers | [rivers and lake centerlines](https://www.naturalearthdata.com/downloads/10m-physical-vectors/10m-rivers-lake-centerlines/) | vector |
| @sec-rivers | [rivers, Europe supplement](https://www.naturalearthdata.com/downloads/10m-physical-vectors/10m-rivers-lake-centerlines/) | vector |
| @sec-rangemap | [Rangemap Erebia albergana](https://www.iucnredlist.org/search?query=Erebia%20albergana&searchType=species) | vector |
| @sec-occurrence | [GBIF *Erebia alberganus* occurrence data](https://www.gbif.org/species/5134543) | vector |
| @sec-climatedata | [Worldclim historical climate data](https://www.worldclim.org/data/worldclim21.html#) | raster |
| @sec-obtainfutureclimatelayers | [Worldclim future climate data](https://www.worldclim.org/data/cmip6/cmip6climate.html) | raster |
| @sec-landcover | [CORINE Land cover (CLC)](https://land.copernicus.eu/en/products/corine-land-cover) | raster/vector |

: {tbl-colwidths="\[20,60,20\]"}

### Other data sources {.unnumbered}

The list below provide a few potentially useful data sources.

| Variable | Name + link |
|------------------------------------|------------------------------------|
| Altitude | [Copernicus DEM](https://dataspace.copernicus.eu/explore-data/data-collections/copernicus-contributing-missions/collections-description/COP-DEM) |
| Climate data | [ClimateEU: historical and projected climate data for Europe](https://sites.ualberta.ca/~ahamann/data/climateeu.html) |
| Climate data | [The ECLIPS-2.0 dataset, High-resolution gridded climate data for Europe](https://zenodo.org/records/3952159) |
| Climate data | [Climate Data Store](https://cds.climate.copernicus.eu/datasets) |
| Climate data | [CHELSA high resolution climate data](https://www.chelsa-climate.org/) |
| Climate data | [TerraClimate, monthly climate and climatic water balance](https://www.climatologylab.org/terraclimate.html) |
| Climate data | [CliMond, global climatologies for bioclimatic modelling](https://www.climond.info/) |
| Land cover and use | [Sentinel-2 10-Meter Land Cover](https://livingatlas.arcgis.com/landcover/) |
| Land cover and use | [LUCAS Land use and land cover survey](https://ec.europa.eu/statistical-atlas/viewer/?config=LUCAS-2015.json) |
| Land cover and use | [Land Cover Map of Europe 2017](https://s2glc.cbk.waw.pl/extension) |
| Land cover and use | [ESA Worldwide land cover mapping](https://esa-worldcover.org/) |
| Land cover and use | [Landelijk grondgebruik Nederland](https://lgn.nl/) |
| Ecosystems | [Ecosystem types of Europe](https://www.eea.europa.eu/en/datahub/datahubitem-view/573ff9d5-6889-407f-b3fc-cfe3f9e23941) |

: {tbl-colwidths="\[30,70\]"}

<br>