# The basic steps {#sec-basics}

In this part, we introduce the basic workflow of species distribution modeling. We start with acquiring and importing data (section [2](#sec-data)), followed by data preparation (section [3](#sec-dataprep)). Next, we train, validate, and evaluate distribution models (section [4](#sec-modeltraining)). Finally, we use these models to predict the potential future distribution of the almond-eyed ringlet butterfly (section [5](#sec-modelprediction)). By the end of this part, you will be able to build a species distribution model using Maxent and to visualise and interpret the results.

![The four main steps in species distribution modeling and the corresponding GRASS GIS addon[^the_basics-1].](images/modeling_workflow.png){#fig-modeling_workflow fig-align="left"}

[^the_basics-1]: The rationale for having separate addons for each step is to encourage and help the user to carefully consider the assumptions and considerations at each stage of the modeling process. The tutorial follows the same structure.

[^the_basics-2]: The rationale for having separate addons for each step is to encourage and help the user to carefully consider the assumptions and considerations at each stage of the modeling process. The tutorial follows the same structure.

This is only the starting point of your journey into species distribution modeling. In practice, model development is an iterative process that involves fine-tuning. This may include experimenting with different input data, adjusting model parameters, and comparing model performance to identify the most suitable model or set of models for a given question. Several of these advanced steps are addressed in the second part of this reader, *Beyond the basics*, where we explore methods for improving and validating species distribution models in more detail.

<!-- Read the Formbutton docs at formspree.io/formbutton/docs. See more examples at codepen.io/formspree -->

```{=html}
<script src="https://formspree.io/js/formbutton-v1.min.js" defer></script>
```

```{=html}
<script>
  /* paste this line in verbatim */
  window.formbutton=window.formbutton||function(){(formbutton.q=formbutton.q||[]).push(arguments)};
  /* customize formbutton below*/     
  formbutton("create", {
    action: "https://formspree.io/f/xjvppyvg",
    title: "Feedback", 
    fields: [
      { 
        type: "email", 
        label: "Email:", 
        name: "email",
        required: true,
        placeholder: "your@email.com"
      },
      {
        type: "hidden",
        label: "",
        value: "sdmingrass - 1 Introduction",
      },
      {
        type: "textarea",
        label: "Message:",
        name: "message",
        placeholder: "Question or feedback? Send a message.",
      },
      { type: "submit" }      
    ],
    styles: {
      title: {
        backgroundColor: "#57B444"
      },
      button: {
        backgroundColor: "#57B444"
      }
    }
  });
</script>
```
